backend:
  name: git-gateway
  branch: main # 確保這是你的主要分支名稱

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "news"
    label: "潮流新聞 (News)"
    folder: "content/news"
    create: true
    fields:
      - { label: "語言", name: "language", widget: "select", options: ["zh", "en", "ja"] }
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "封面圖片", name: "image", widget: "image" }
      - { label: "內容", name: "body", widget: "markdown" }
